{
  "formatVersion": "1.1",
  "component": {
    "group": "com.stzteam.features.unitprocessor",
    "module": "UnitProcessor",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UnitProcessor-1.0.4.jar",
          "url": "UnitProcessor-1.0.4.jar",
          "size": 5928,
          "sha512": "a22434062308b25b558adc9f45c1cbc253d4f55de75337155bb55f994fc926a8cba789c5cd1e72c520711585c267adc55e98ca6dece90e6ff47b65abc502fa60",
          "sha256": "7f99c6bb68e81f8bda8cfc7e7b5eac77898194f08acd6b8f93a8cbaeb0bd9139",
          "sha1": "f43978cd6d31c48e744b569b5e7be5a20f38f21b",
          "md5": "2e9a9d20f80396415e29b9131561c46a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpinet",
          "module": "wpinet-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.apriltag",
          "module": "apriltag-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.epilogue",
          "module": "epilogue-runtime-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2025.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.10.0-3"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.44.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        },
        {
          "group": "us.hebi.quickbuf",
          "module": "quickbuf-runtime",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.1.1"
          }
        },
        {
          "group": "com.stzteam.forgemini",
          "module": "ForgeMini",
          "version": {
            "requires": "[1.1.0,)"
          }
        },
        {
          "group": "com.stzteam.mars",
          "module": "Mars",
          "version": {
            "requires": "[1.6.0,)"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "UnitProcessor-1.0.4.jar",
          "url": "UnitProcessor-1.0.4.jar",
          "size": 5928,
          "sha512": "a22434062308b25b558adc9f45c1cbc253d4f55de75337155bb55f994fc926a8cba789c5cd1e72c520711585c267adc55e98ca6dece90e6ff47b65abc502fa60",
          "sha256": "7f99c6bb68e81f8bda8cfc7e7b5eac77898194f08acd6b8f93a8cbaeb0bd9139",
          "sha1": "f43978cd6d31c48e744b569b5e7be5a20f38f21b",
          "md5": "2e9a9d20f80396415e29b9131561c46a"
        }
      ]
    }
  ]
}
